### ISSUE TITLE
Number Features Tool Bug

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#189]
@jscott11 , I've been working w/ @rbernstein to develop her Compound Map template, and we've found an issue with the Number Features tool.

It works great if you actually assign an *Area to Number*, but if you assign a layer incorrectly (one that's not an area), it will run "successfully" and delete the features in your *Point Features* layer.

It would be great if it either only allowed you to choose an actual polygon layer for *Area to Number*, or presented a warning. Also, if it didn't delete the features regardless of input, I think that'd be for the best.

@rbernstein , if you have any other insight on this issue, please say so (can you include a screenshot here?).

Thanks!

**Comment by BobBooth** [comment]
As I recall, it also deletes the points that fall outside of the Area to Number, if you give it a real area. This seems like a bad idea.

**Comment by joebayles** [comment]
Agreed. Here's a screenshot from @rbernstein ... the points were on every building in the compound. After the tool ran successfully, the only result was the points in the actual polygon (in blue). Points that were inside the perimeter (in red) or around the map (outside of blue or red) were deleted.

![screenshot](https://cloud.githubusercontent.com/assets/5016557/5765532/27575662-9caf-11e4-9cfb-8855505d282a.png)

**Comment by nfeuerstein** [comment]
Is it creating a copy and then deleting the points that fall outside the area?  Or does it delete the points from the original point feature class?

**Comment by joebayles** [comment]
If you identify an output feature class, it will create that output feature class (without any features that weren't in the Area to Number, as intended). When it does that, however, it deletes the points from the original point feature class, which is NOT intended.

If you do not identify an output feature class, it overwrites the input point feature class (as intended).
![image](https://cloud.githubusercontent.com/assets/5016557/5766628/eb8d3580-9cb7-11e4-993c-61143556e29d.png)
However, it will still delete the points from the original point feature class, which again, is NOT intended.

**Comment by jscott11** [comment]
Progress! 

I modified this so that it will throw an error if a polygon is not chosen for the Area.

In addition, if you do not identify an output feature class, it will keep the points in the original feature class now.  (As you can see - 4,6, and 8 were not in the area I selected.)
![overwrite](https://cloud.githubusercontent.com/assets/6684379/6273721/969690dc-b83f-11e4-89bb-55c6746dc51b.JPG)


However, if you specify an output feature class, I can't get your other issue to reproduce. If I have 8 features in my original class (pink dots below)
![testbase](https://cloud.githubusercontent.com/assets/6684379/6273753/d097a10e-b83f-11e4-90ea-3ce702c94a71.JPG)
, and then select 5 of the dots, it creates the yellow dots output with 5, but also keeps all 8 pink dots. (5 are hidden under the yellow, but they are there) 
![testdelete](https://cloud.githubusercontent.com/assets/6684379/6273760/e3c1acf2-b83f-11e4-84d9-75ad5096738c.JPG)


@joebayles  Is there another way I can test this? or I may just be totally not understanding this haha. 
When you have a chance can you retest the other issues that are fixed too?

**Comment by joebayles** [comment]
:+1: @jscott11 
@rbernstein, since you're working on your template now, can you test this? If not, I'll get around to it.

**Comment by jrweakland** [comment]
@rbernstein - please test his when you come to Redlands.

**Comment by mfunk** [comment]
This one has been hanging for a few months and is supposed to be fixed. Closing this until it cannot be verified as fixed.
