### ISSUE TITLE
Incident Analysis - Count Incidents by LOC output should never be blank

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#322]
The Count Incidents by LOC tool in the Incident Analysis toolbox produces a line feature class output..If the frequency count is 0, you get a value of null.. Two related thoughts on this... If the value is 0, I think we should show 0 instead of null...follow on to that, if the value is 0, it is not going to display at all on the map... should we drop rows with a frequency count from the table? Personally i like having a value of 0 but keeping them in the table so the user atleast knows the tool ran correctly, in the case that all rows were 0 and they were removed from the feature class, the user may be concerned that the tool did not run properly.Maybe when this is ready to be worked on, we can have a short meeting to decide which decision we actually want to go with.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043932861)

**Comment by mfunk** [comment]
Easy enough to add a few steps to select all <Null> records in FREQUENCY and calculate them to be 0. 

![image](https://cloud.githubusercontent.com/assets/3093182/25361071/0dde8648-2901-11e7-8bdd-e2a13aa0d3b2.png)

![image](https://cloud.githubusercontent.com/assets/3093182/25361124/578dfa8a-2901-11e7-9876-77a534cb394f.png)


Also found that the output layer symbology labels in the first class were statically set to be 5 - 10 instead of the actual values 1 - 10.

![image](https://cloud.githubusercontent.com/assets/3093182/25361054/f1d31e00-2900-11e7-833a-2d5ca7962ab5.png)

**Comment by mfunk** [comment]
@dfoll Fixed but need you to check that its what you expect. Thanks.
