### ISSUE TITLE
Incident Density does not respect layer definition queries

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#483]
Run the Incident Density tool on the last 30 days layer.  
Now run the Incident Density tool on the month before last layer.
The results are the same.
Compare this to running the Buffer tool on the same two layers. Buffer respects the definition query, Incident Density does not.

## Expected Behavior
I would expect the tool to respect the definition query on the layer.

## Your Environment
Incident Analysis 4.0.1 - ArcMap 10.5.0

**Comment by mfunk** [comment]
@BobBooth So does **Incident Density** use ALL of the from the layer, instead of the data filtered by the Def. Query? When it does NOT honor it, what is the output? Trying to write up the Known Issues list for IA and want to include this.

**Comment by mfunk** [comment]
So it seems it is using the full list of data points, though the analysis option to snap to features is reducing the number from 5532 initial data points down to 1961 data points. The option we set in the tool is:

```
SNAP_NEARBY_INCIDENTS_TO_CREATE_WEIGHTED_POINTS —Nearby incidents will be aggregated together to create a single weighted point. The weight for each point is the number of aggregated incidents at that location.
```
So the ICOUNT field shows how many points were aggregated together. A quick summary on that field shows that it was made from ALL of the original data ponits.

```
Count:	1961
Minimum:	1
Maximum:	50
Sum:	5532
Mean:	2.82101
Standard Deviation:	3.474697
Nulls:	0
```

**Comment by Dbarnes1** [comment]
I can replicate this issue, going to explore further

**Comment by Dbarnes1** [comment]
Waiting on a response from GP folks, but right now it seems like the Optimized Hot Spot Analysis tool that is included in both the ArcMap and Pro versions of this model may automatically bypass layer definition queries, and run on the entire dataset. 

If this is the case, then the question becomes: Does changing the tool to enable definition queries defeat the purpose of calculating incident density? After all, wouldn't they just use Emerging Hot Spot Analysis in Pro if they wanted to filter/explore the layer by time? If users wanted to run Optimized Hot Spot Analysis on a subset of their data, they could specify an analysis field instead of aggregating all points by weighted values. Could we surface that analysis field as a parameter in our model? Either way we need to link to the Optimized Hot Spot Analysis tool doc in both our tool documentation and IA template documentation so people better understand what the tools do.

**Comment by Dbarnes1** [comment]
According to the team that maintains the OHSA tool, it should respect layer definition queries, and when I run the OHSA tool out of the box, I'm getting an error about a missing OID field on the definition query layers. 

This issue is related to https://github.com/Esri/solutions-geoprocessing-toolbox/issues/521 and the common denominator is that they both primarily rely on OHSA. Still looking for a potential fix to both tools

**Comment by Dbarnes1** [comment]
Found easy workaround and fix for #521, but this is still an issue

**Comment by BobBooth** [comment]
@Dbarnes1 & @mfunk  - an easy fix for this might be to copy the input features to a new, in_memory feature class before running the rest of the tool on it - that copy features would respect definition queries of any sort (should anyway) and would also add a new OID field that would solve https://github.com/Esri/solutions-geoprocessing-toolbox/issues/521

**Comment by Dbarnes1** [comment]
@BobBooth is correct, here is the output once you add copy features:
All Incidents:
![image](https://user-images.githubusercontent.com/13024357/28677768-646e761c-72a3-11e7-868c-6c5e544bc4dc.png)
Last 30 days:
![image](https://user-images.githubusercontent.com/13024357/28677792-75120a10-72a3-11e7-942a-bd0a37a4ed60.png)
I'll be submitting a PR with the improved version of the Incident Density tool later on.

**Comment by BobBooth** [comment]
At least in ArcMap 10.5, the feature class to feature class step has to happen before the Project features step. Project does not seem to respect the definition query, but FC to FC does.
![image](https://user-images.githubusercontent.com/3801392/28679232-8a2caf96-72c0-11e7-9966-092efa647b58.png)

**Comment by Dbarnes1** [comment]
I removed the associated known issue from the documentation

**Comment by Dbarnes1** [comment]
@BobBooth this will be ready to verify once the PR is merged in both the map and pro toolboxes

**Comment by csmoore** [comment]
Verified - I got the same results [shown as correct above](https://github.com/Esri/solutions-geoprocessing-toolbox/issues/483#issuecomment-318392669) (Tested on 10.4)

![image](https://user-images.githubusercontent.com/3090809/28840333-aba7c3d8-76c4-11e7-85ac-67978d8485fe.png)

![image](https://user-images.githubusercontent.com/3090809/28840351-b60930e6-76c4-11e7-9f1c-96477317c1ad.png)
