### ISSUE TITLE
Incident Analysis - Toolbox Enhancements

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#495]
### Cluster Analysis Tool
- [x] Add a description to the **Output Cluster Features** dialog (Map and Pro)
- [x] Change the value display name from `ICOUNT `to `Incident Count`
- [ ] ~~Remove the decimals from the legend~~

### Incident Hot Spot
- [x] Change the value display name from `Gi_Bin` to `Hot Spot Confidence`

### Hot Spot by Area
- [x] Change the Output Filename from `Selectvalue_OptimizedHotSpot` to `Dn_Hotspot` (where _n_ is the District #)
- [x] Change the value display name from `Gi_Bin` to `Hot Spot Confidence`

### Incident Density
- [x] Add a description to the **Spatial Reference** dialog
- [x] Change the Feature value display name from `Gi_Bin` to `Hot Spot Confidence`
- [ ] Change the Output Density Overlay value display name from `Value` to `Incidence`
- [x] Change the Output Density Overlay color scheme from black-white to green-red

### Incidents by LOC
- [x] Change the Feature value display name from `FREQUENCY` to `Incident Frequency`

### Percent Change
- [ ] Change the Feature value display name from `PrecentChange` to `Percent Change`
- [ ] ~~Add `%` to values in the legend~~

#### FYI
@mfunk @Dbarnes1 @BobBooth @elinz @migueldls

**Comment by mfunk** [comment]
Interestingly I can see the IA Pro model tools in ArcMap 10.3. Usually this is not the case. So I'm going to proceed and try to make the fixes for both toolboxes (Pro and Map) in ArcMap.
Cross your fingers people.

**Comment by mfunk** [comment]
Cluster Analysis... so I can fix everything but the decimals, apparently these are dynamic. So I can change the layer before:
![image](https://cloud.githubusercontent.com/assets/3093182/25713872/0743641e-30ab-11e7-9758-09a38d7a09fc.png)
... and save it as a .LYR, then reapply that to the output parameter in the model. But when the tool is run the output dynamically picks up the values for the legend:
![image](https://cloud.githubusercontent.com/assets/3093182/25713909/299d257c-30ab-11e7-8303-c1951184cd53.png)

**Comment by joebayles** [comment]
I had a feeling that was going to be the case. Cool, it is what it is.

**Comment by mfunk** [comment]
## Incident Hot Spots
Inconsistency on the part of ArcGIS Pro. So I made the suggested change to the legend subtext ("Hot Spot Confidence" instead of "Gi_Bin") in ArcMap  and no problem, model picks it up and uses it for the output. However in ArcGIS Pro it ignores the .LYRX subtext and goes back to "Gi_Bin" when you run the tool. But if you drag and drop the .LYRX into Pro's map, it says "Hot Spot Confidence". I've tried three or four times setting the .LYRX as the Output Symbology in the IHS model parameters, but it doesn't seem to make a difference here. This wasn't a problem for Cluster Analysis so I'm not sure if this is a problem because a different feature renderer is used behind the symbology (Graduated Colors vs. Graduated Symbols). Unfortunately this is another one I cannot explain.

**Comment by joebayles** [comment]
Some more feedback for the Pro team...

**Comment by joebayles** [comment]
@mfunk FYI, I just heard back from the documentation team. For optional parameters, we've been doing the right thing. Just to confirm though, because we might have a few to clean up, it should be:
Left:
Parameter Title(optional)

Right:
**Parameter Title**
Optionally, …

**Comment by mfunk** [comment]
@joebayles perhaps I'm missing something on your last comment, not sure I understand what Left/Right you're talking about.

**Comment by joebayles** [comment]
@mfunk Sorry, that was vague. By left and right, I mean the tool parameters and the tool doc.
![image](https://cloud.githubusercontent.com/assets/5016557/25817619/bebe260e-33dc-11e7-8637-9140a20f062c.png)

**Comment by mfunk** [comment]
I think I get it. However on the left the "(optional)" text is not part of the title, it is added by the UI when it detects a parameter that is marked optional:
![image](https://cloud.githubusercontent.com/assets/3093182/25818661/2ee8a636-33e0-11e7-88dd-6696efe71d5c.png)

**Comment by mfunk** [comment]
# Incident Density

Found a problem while fixing Incident Density. Apparently the Optimized Hot Spot Analysis (OHSA) tool doesn't like %scratchGDB% in the default output path. Kinda hard when you don't want to hardcode a path.

![image](https://cloud.githubusercontent.com/assets/3093182/25820272/8f40417e-33e5-11e7-8c92-c2a701a27aa3.png)


* Fixed tool help descriptions.
* The ```Value``` label in the stretch renderer for Output Density Overlay cannot be changed (don't know if it is a limitation in Pro or oversight on responsible team.
* Output color ramp for Output Density Overlay is already green-to-red in output...

![image](https://cloud.githubusercontent.com/assets/3093182/25820678/fb4e6ae8-33e6-11e7-975f-5bae95dbd383.png)

**Comment by mfunk** [comment]
# Count Incidents By LOC

- Neither Pro nor ArcMap have a Spatial Reference option:
![image](https://cloud.githubusercontent.com/assets/3093182/25828441/06b2b54c-3405-11e7-8a55-1b07747c201d.png)

**Comment by mfunk** [comment]
# Find Percent Change

Another case where we can't statically label a dynamic tool result. Since the output number values change when the tool is run we can't use the .LYR/.LYRX to add a "%" sign to the labels.
![image](https://cloud.githubusercontent.com/assets/3093182/25828836/58a66752-3407-11e7-8e49-9456aaa3444c.png)

**Comment by joebayles** [comment]
Verified.
