### ISSUE TITLE
Compound Map and Clearing Operations Number features tools should be able to add number field

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#543]
The Number features tool in the Compound Map and Clearing Operations toolboxes/solutions requires an input point feature class to number. However, it also expect the user to have added a field called Number (of type Short) to the data.  It seems reasonable that the tool could be configured to require less setup by the user, and just add a field for the numbers.

## Possible Solution
Include adding a field to the output number features feature class to which to add the numbers.
Resulting feature class should have all of the original input feature class fields plus a new Number field with sequential numbers in it.

ArcGIS Pro 2.0

**Comment by topowright** [comment]
This is a known issue in ArcGIS Pro 2.0 and is being fixed by core in ArcGIS Pro 2.1

**Comment by adgiles** [comment]
Lyle, I think you maybe confusing what Bob is suggesting here with something else. The enhancement that  Bob is proposing is that the underlying script creates a new field with the structure numbers in it; instead of the field having to already exist in the feature class and the user select it during the tool settings.

**Comment by topowright** [comment]
@BobBooth this fix has been addressed in the following pull request: 
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/578

please verify once the PR has been accepted.

**Comment by BobBooth** [comment]
@topowright - I was trying to test this, with the latest, and seeing a recurrence of https://github.com/ArcGIS/solutions-defense/issues/403

**Comment by BobBooth** [comment]
@topowright - also, when I add the LYR file to ArcMap to look at the symbology, it seems to have only one category, yellow square symbol, and the layer name is "asdfasde" - this is both the LYR file in this repo and the one in the staging folder.
![image](https://user-images.githubusercontent.com/3801392/30225011-e19acd80-949e-11e7-9366-5c191eb21172.png)

**Comment by BobBooth** [comment]
@mfunk - something to have a look at as you migrate the tools.

**Comment by topowright** [comment]
This issue can be verified once the following pull request is merged: 
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/596

**Comment by topowright** [comment]
This issue is tracking two issues. 
The first issue addresses that  a user should be able to use a feature class that does not have a short field in the table when they run the tool. Before #578 this was not possible. This is now a part of the tools capability. 

The second issue addresses the layer file output. This is what now can be verfied after pull request #596 is merged.

**Comment by topowright** [comment]
This issue can be closed based on the following pull request #596 , which was verified by @BobBooth today.
