### ISSUE TITLE
Clearing Operations Point target GRG failing

### ISSUE THREAD

**Issue by pHill5136** [Esri/solutions-geoprocessing-toolbox#557]
ExecuteError: Executing: CopyFeatures in_memory\tempSort Alpha-Numeric # 0 0 0
Start Time: Fri Aug 04 09:38:47 2017
ERROR 000210: Cannot create output Alpha-Numeric
Failed to execute (CopyFeatures).
Failed at Fri Aug 04 09:38:47 2017 (Elapsed Time: 0.02 seconds)
Failed to execute (Point Target GRG Script).
Failed to execute (PointTargetGRG).

Tool failing to execute. Error I'm receiving above.

**Comment by adgiles** [comment]
Patrick, it's nothing to do with \tempSort being seen as a tab by python is it?

**Comment by mfunk** [comment]
Point Target GRG Script tool
The problem is the parameter order in the script tool () is not matching the expected order in the script (PointTargetGRG.py).

* Target Point of Origin
* Number of Grid Cells - Horizontal
* Number of Grid Cells - Vertical
* Cell Width
* Cell Height
* Cell Units
* Grid Size
* Labeling Start Position
* Labeling Style
* Output Name


The order in the script is:
```
targetPointOrigin = arcpy.GetParameterAsText(0)
numberCellsHo = arcpy.GetParameterAsText(1)
numberCellsVert = arcpy.GetParameterAsText(2)
cellWidth = arcpy.GetParameterAsText(3)
cellHeight = arcpy.GetParameterAsText(4)
cellUnits = arcpy.GetParameterAsText(5)
gridSize = arcpy.GetParameterAsText(6)
labelStyle = arcpy.GetParameterAsText(7)
outputFeatureClass = arcpy.GetParameterAsText(8)
labelStartPos = arcpy.GetParameterAsText(9)
```

Basically the last two parameters/arguments are getting swapped and we get the error. Though the last three are actually incorrect as well.

So the argument list should go in sequence:
* Input before output
* Required before optional

So the order in the SCRIPT should actually be (where last three are switched):

```
targetPointOrigin = arcpy.GetParameterAsText(0)
numberCellsHo = arcpy.GetParameterAsText(1)
numberCellsVert = arcpy.GetParameterAsText(2)
cellWidth = arcpy.GetParameterAsText(3)
cellHeight = arcpy.GetParameterAsText(4)
cellUnits = arcpy.GetParameterAsText(5)
gridSize = arcpy.GetParameterAsText(6)
labelStartPos = arcpy.GetParameterAsText(7)
labelStyle = arcpy.GetParameterAsText(8)
outputFeatureClass = arcpy.GetParameterAsText(9)
```

**Comment by mfunk** [comment]
Try to get this one in with #556.
