### ISSUE TITLE
Issues with lyr files and output work spaces for Incident Analysis

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#606]
lyr files have bad link for Find percent change
lyr files have bad link for Incident Density

Incident Density is writing to a GDB and fails. The default output might help if it is pushed to a workspace. 
## Current Behavior

![image](https://user-images.githubusercontent.com/5488313/30667335-08b7652e-9e0c-11e7-996c-5c027be67f19.png)
![image](https://user-images.githubusercontent.com/5488313/30667346-1166a842-9e0c-11e7-9482-b2121877a6e5.png)
![image](https://user-images.githubusercontent.com/5488313/30667357-18812cb0-9e0c-11e7-9fb6-962e9ba6f41e.png)

## Possible Solution

update layerfile link in models
change output to workspace
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by csmoore** [comment]
Most of these ended up being actual deployment/packaging issues (the template layer files did not match this repo - I didn't know the layer files had also changed when I created the package).

The only one above that can not be solved on the packaging end is the default parameter issue with Incident Density. But seems like an enhancement since the tools runs as designed once the parameters is set:

![image](https://user-images.githubusercontent.com/3090809/30697751-095cdbe2-9eae-11e7-9605-e0c03610f298.png)

But if run outside the template all of these parameters need supplied so perhaps that can be recorded as another issue/enhancement :

![image](https://user-images.githubusercontent.com/3090809/30698183-29c49a5e-9eaf-11e7-8ae7-0c5950a597ba.png)

The Pro tool also has a step that can probably be removed that references an ArcMap layer file:

![image](https://user-images.githubusercontent.com/3090809/30697873-56243f10-9eae-11e7-804b-7d09e1ad3b82.png)

I will close this issue if I don't hear back.

**Comment by topowright** [comment]
I can take a look at this, but I thought this was solved by making a new lyrx file.

**Comment by csmoore** [comment]
This was an issue with the template that was resolved with repackaging - this can probably be closed - setting to verify

**Comment by topowright-zz** [comment]
This issue has been verified. 

![image](https://user-images.githubusercontent.com/5488313/49445452-cd7d0100-f786-11e8-9ce0-a63b2ce17062.png)
