### ISSUE TITLE
NumberFeatures tool does not label feature correctly when new feature class is created

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-geoprocessing-toolbox#677]
6/13: Tasks remaining
- [ ] Add tool to MT toolbox
- [ ] Test from MT build
- [ ] Doc GRG toolset topic - add Number Features to table
- [ ] MT What's new (added the tool to GRG toolset)

When creating a new feature layer (feature class) during the Number Feature tool process, the tool:
1. Creates a new feature class in the project GDB
2. Adds it as a feature layer to the TOC
3. Applies the appropriate layer file for symbology
But, the features are not labeled at all. Somehow the layer file is preventing it from labeling.

## Expected Behavior
Features should be labeled in the newly created feature layer

## Current Behavior
Run tool on:
![image](https://user-images.githubusercontent.com/3801392/41122837-d42fa60a-6a6a-11e8-804a-cc9b8464077a.png)
Get result:
![image](https://user-images.githubusercontent.com/3801392/41122861-e5df2cae-6a6a-11e8-8a49-3a6914f87302.png)
Features are not labeled.

## Possible Solution
Update LYRX file to provide labels as well as symbology.

## Steps to Reproduce (for bugs)
1. Open the Clearing Operations solution
2.  Open the Number features tool 
3. Choose to number the NewLocations feature layer
4. Specify a new output feature class
5. Run the tool.
6. The new layer is added to the map. It has the correct symbology, but the features are not labeled.
7. Turn on labels - for some reason, even when you turn on labels they don't display (though sometimes they do.  @kgonzago  and @ACueva saw it not working, then I (BB) tried again on my own ArcGIS Pro 2.1.0 machine and I could manually apply labels and have them display). 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:
Win10, ArcGIS Pro 2.1.
Win8, ArcGIS Pro 2.1.0 (BB)

**Comment by csmoore** [comment]
I ran this on Pro 2.2.12776(Beta2) and setting the symbology/labeling on the output layer using a lyrx file seems to be now working correctly for setting the labels. So **this issue is dependent on Pro 2.2 final**:

![image](https://user-images.githubusercontent.com/3090809/41308402-c3a31866-6e49-11e8-8736-bf774717e7eb.png)

There is just a small code change needed ([here](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/clearing_operations/scripts/NumberFeaturesTool.py#L93)) to check whether in Pro or ArcMap because a Pro .lyrx file is needed to make the GP output labeling work (a 10.X .lyr file doesn't work for this labeling scenario)

Moving/migrating NumberFeatures tool opened with issue: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/339

FYI @topowright @BobBooth @dfoll @ACueva

**Comment by BobBooth** [comment]
@csmoore - cool!  So, an if product == ArcMap use lyr, if product == Pro use lyrx check here is all it would need?

**Comment by csmoore** [comment]
@BobBooth - that is correct. There is an [existing method/utility](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/clearing_operations/scripts/Utilities.py#L41) for this - though its behavior is not consistent if run from arcpy outside of the Pro/ArcMap - since it returns: 1. Pro 2. ArcMap 3. Other (standalone arcpy but could be Pro or ArcMap python) - so we may need to add a method

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/military-tools-geoprocessing-toolbox#341
